<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="myPool" tests="3" failures="1" errors="0" time="35.757" skipped="2" timestamp="2018-11-08T11:19:01">
  <testcase name="test1" time="11.919" classname="com.example">
    <failure><![CDATA[Exception in thread "main" java.lang.RuntimeException: A test exception
  at com.example.stacktrace.StackTraceExample.methodB(StackTraceExample.java:13)
  at com.example.stacktrace.StackTraceExample.methodA(StackTraceExample.java:9)
  at com.example.stacktrace.StackTraceExample.main(StackTraceExample.java:5)]]></failure>
  </testcase>
  <testcase name="test2" time="11.919" classname="com.example">
    <skipped></skipped>
  </testcase>
  <testcase name="test3" time="11.919" classname="com.example">
    <skipped><![CDATA[Exception in thread "main" java.lang.RuntimeException: A test exception
  at com.example.stacktrace.StackTraceExample.methodB(StackTraceExample.java:13)
  at com.example.stacktrace.StackTraceExample.methodA(StackTraceExample.java:9)
  at com.example.stacktrace.StackTraceExample.main(StackTraceExample.java:5)]]></skipped>
  </testcase>
</testsuite>
